name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'Nofraud'
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "lts/*"
      - run: npm install -g semantic-release @semantic-release/github @semantic-release/git @semantic-release/changelog @iwavesmedia/semantic-release-composer
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
