name: Check composer.json Version Bumped
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changes 
        run: |
          echo $(git log --pretty=format:"%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})


