name: Check composer.json Version Bumped
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for releasable commit messages 
        run: |
          commits=$(git log --pretty=format:"%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          if [[ $commits =~ "fix" || $commits =~ "feat" ]]; then
            echo "Commit messages contain 'fix' or 'feat'. Running file check..."
          else
            echo "Skipping further checks as this PR would not generate a release."
            exit 0
          fi
      - name: Check Version Key Update
        id: check_version_changes
        run: |
          changed_lines=$(git diff -r --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- composer.json | grep -c "version")
          if [ "$changed_lines" -eq "0" ]; then
            echo "Error: version in composer.json must be updated in the pull request"
            exit 1
          fi


